/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_v1_runs__run_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take Action */
        post: operations["take_action_v1_runs__run_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory Lineage */
        get: operations["get_memory_lineage_v1_runs__run_id__memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/memories/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recall Memories */
        post: operations["recall_memories_v1_runs__run_id__memories_recall_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRequest */
        ActionRequest: {
            /**
             * Idempotency Key
             * Format: uuid
             */
            idempotency_key: string;
            verb: components["schemas"]["ActionVerb"];
            /** Target Id */
            target_id?: string | null;
            /** Content */
            content?: string | null;
        };
        /** ActionResponse */
        ActionResponse: {
            /**
             * Action Id
             * Format: uuid
             */
            action_id: string;
            /** Consumed Time */
            consumed_time: boolean;
            snapshot: components["schemas"]["RunSnapshot"];
        };
        /**
         * ActionVerb
         * @enum {string}
         */
        ActionVerb: "move" | "observe" | "read_notice_board" | "talk" | "promise_help" | "confront" | "sleep";
        /** BeliefInputState */
        BeliefInputState: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Proposition Key */
            proposition_key: string;
            /** Holder Id */
            holder_id: string;
            /** Source Kind */
            source_kind: string;
            /** Source Id */
            source_id: string | null;
            /** Narrative Text */
            narrative_text: string;
            /** Normalized Position */
            normalized_position: {
                [key: string]: unknown;
            };
            /** Source Trust */
            source_trust: number;
            /** Evidence Weight */
            evidence_weight: number;
            /** Corroboration */
            corroboration: number;
            /** Recency */
            recency: number;
            /** Bias Alignment */
            bias_alignment: number;
            /** Incoming Strength */
            incoming_strength: number;
            /** Classification */
            classification: string;
            /** Outcome */
            outcome: string;
            /** Rationale */
            rationale: string;
            /** Observed Version */
            observed_version: number | null;
            /** Evaluated Against Version */
            evaluated_against_version: number | null;
            /** Resulting Belief Id */
            resulting_belief_id: string | null;
            /** Resulting Version */
            resulting_version: number | null;
            /** Transaction Attempts */
            transaction_attempts: number;
            /** Recalculated After Conflict */
            recalculated_after_conflict: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /**
             * Display Name
             * @default Newcomer
             */
            display_name: string;
            /**
             * Seed
             * @default 1729
             */
            seed: number;
        };
        /** CreateRunResponse */
        CreateRunResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            snapshot: components["schemas"]["RunSnapshot"];
        };
        /** DialogueMemoryRef */
        DialogueMemoryRef: {
            /**
             * Belief Id
             * Format: uuid
             */
            belief_id: string;
            /** Version */
            version: number;
            /** Proposition Key */
            proposition_key: string;
            /**
             * Contested
             * @default false
             */
            contested: boolean;
        };
        /** DialogueState */
        DialogueState: {
            /** Speaker Id */
            speaker_id: string;
            /** Speaker Name */
            speaker_name: string;
            /** Text */
            text: string;
            /** Recalled Memories */
            recalled_memories?: components["schemas"]["DialogueMemoryRef"][];
            /** Provider Id */
            provider_id?: string | null;
            /** Model Id */
            model_id?: string | null;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
            /** Fallback Reason */
            fallback_reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocationState */
        LocationState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: [
                number,
                number,
                number
            ];
            /**
             * Neighbors
             * @default []
             */
            neighbors: string[];
        };
        /** MemoryLineageResponse */
        MemoryLineageResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Proposition Key */
            proposition_key?: string | null;
            /** Versions */
            versions: components["schemas"]["MemoryVersionState"][];
            /** Transmissions */
            transmissions: components["schemas"]["TransmissionState"][];
            /** Inputs */
            inputs: components["schemas"]["BeliefInputState"][];
        };
        /** MemoryRecallRequest */
        MemoryRecallRequest: {
            /** Holder Id */
            holder_id: string;
            /** Query */
            query: string;
            /**
             * Limit
             * @default 8
             */
            limit: number;
        };
        /** MemoryRecallResponse */
        MemoryRecallResponse: {
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Holder Id */
            holder_id: string;
            /** Query */
            query: string;
            /** Memories */
            memories: components["schemas"]["RecalledMemory"][];
        };
        /** MemoryVersionState */
        MemoryVersionState: {
            /**
             * Belief Id
             * Format: uuid
             */
            belief_id: string;
            /** Version */
            version: number;
            /** Proposition Key */
            proposition_key: string;
            /** Holder Id */
            holder_id: string;
            /** Narrative Text */
            narrative_text: string;
            /** Normalized Position */
            normalized_position: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence: number;
            /** Salience */
            salience: number;
            /** Source Kind */
            source_kind: string;
            /** Source Id */
            source_id: string | null;
            /** Embedding Model Id */
            embedding_model_id: string;
            /** Active */
            active: boolean;
            /**
             * Contested
             * @default false
             */
            contested: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /** NpcState */
        NpcState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Location Id */
            location_id: string;
            /** Color */
            color: string;
            /**
             * Relationship
             * @default 0
             */
            relationship: number;
            /** Speech */
            speech?: string | null;
        };
        /** PlayerState */
        PlayerState: {
            /** Display Name */
            display_name: string;
            /** Location Id */
            location_id: string;
            /** Traits */
            traits?: string[];
        };
        /** PromiseState */
        PromiseState: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Promisee Id */
            promisee_id: string;
            /** Content */
            content: string;
            /** Deadline Day */
            deadline_day: number;
            /**
             * Deadline Phase
             * @enum {string}
             */
            deadline_phase: "morning" | "afternoon" | "evening" | "night";
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "kept" | "broken";
        };
        /** RecalledMemory */
        RecalledMemory: {
            /**
             * Belief Id
             * Format: uuid
             */
            belief_id: string;
            /** Version */
            version: number;
            /** Proposition Key */
            proposition_key: string;
            /** Narrative Text */
            narrative_text: string;
            /** Semantic Similarity */
            semantic_similarity: number;
            /** Final Score */
            final_score: number;
            /** Confidence */
            confidence: number;
            /** Salience */
            salience: number;
            /** Source Id */
            source_id: string | null;
            /**
             * Contested
             * @default false
             */
            contested: boolean;
        };
        /** RunSnapshot */
        RunSnapshot: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Seed */
            seed: number;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "completed";
            /**
             * Day
             * @default 1
             */
            day: number;
            /**
             * Phase
             * @default morning
             * @enum {string}
             */
            phase: "morning" | "afternoon" | "evening" | "night";
            /**
             * Action Count
             * @default 0
             */
            action_count: number;
            /**
             * World Tick
             * @default 0
             */
            world_tick: number;
            /**
             * Weather
             * @default clear
             * @enum {string}
             */
            weather: "clear" | "rain";
            player: components["schemas"]["PlayerState"];
            /** Locations */
            locations: components["schemas"]["LocationState"][];
            /** Npcs */
            npcs: components["schemas"]["NpcState"][];
            /** Promises */
            promises?: components["schemas"]["PromiseState"][];
            dialogue?: components["schemas"]["DialogueState"] | null;
            /** Recent Events */
            recent_events?: components["schemas"]["WorldEvent"][];
        };
        /** TransmissionState */
        TransmissionState: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Proposition Key */
            proposition_key: string;
            /** Speaker Id */
            speaker_id: string | null;
            /** Listener Id */
            listener_id: string;
            /** From Belief Id */
            from_belief_id: string | null;
            /** From Version */
            from_version: number | null;
            /**
             * To Belief Id
             * Format: uuid
             */
            to_belief_id: string;
            /** To Version */
            to_version: number;
            /** Original Text */
            original_text: string | null;
            /** Retold Text */
            retold_text: string;
            /** Mutation Note */
            mutation_note: string | null;
            /** Trust At Time */
            trust_at_time: number | null;
            /**
             * Provider Id
             * @default deterministic
             */
            provider_id: string;
            /** Model Id */
            model_id: string;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
            /** Fallback Reason */
            fallback_reason?: string | null;
            /**
             * Inference Attempts
             * @default 0
             */
            inference_attempts: number;
            /** Inference Latency Ms */
            inference_latency_ms?: number | null;
            /** Created At */
            created_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorldEvent */
        WorldEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /**
             * Visible
             * @default true
             */
            visible: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_v1_runs__run_id__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_action_v1_runs__run_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_lineage_v1_runs__run_id__memories_get: {
        parameters: {
            query?: {
                proposition_key?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryLineageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recall_memories_v1_runs__run_id__memories_recall_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryRecallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryRecallResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
