/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_v1_runs__run_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take Action */
        post: operations["take_action_v1_runs__run_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRequest */
        ActionRequest: {
            /**
             * Idempotency Key
             * Format: uuid
             */
            idempotency_key: string;
            verb: components["schemas"]["ActionVerb"];
            /** Target Id */
            target_id?: string | null;
            /** Content */
            content?: string | null;
        };
        /** ActionResponse */
        ActionResponse: {
            /**
             * Action Id
             * Format: uuid
             */
            action_id: string;
            /** Consumed Time */
            consumed_time: boolean;
            snapshot: components["schemas"]["RunSnapshot"];
        };
        /**
         * ActionVerb
         * @enum {string}
         */
        ActionVerb: "move" | "observe" | "read_notice_board" | "talk" | "promise_help" | "confront" | "sleep";
        /** CreateRunRequest */
        CreateRunRequest: {
            /**
             * Display Name
             * @default Newcomer
             */
            display_name: string;
            /**
             * Seed
             * @default 1729
             */
            seed: number;
        };
        /** CreateRunResponse */
        CreateRunResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            snapshot: components["schemas"]["RunSnapshot"];
        };
        /** DialogueState */
        DialogueState: {
            /** Speaker Id */
            speaker_id: string;
            /** Speaker Name */
            speaker_name: string;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocationState */
        LocationState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: [
                number,
                number,
                number
            ];
        };
        /** NpcState */
        NpcState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Location Id */
            location_id: string;
            /** Color */
            color: string;
            /**
             * Relationship
             * @default 0
             */
            relationship: number;
            /** Speech */
            speech?: string | null;
        };
        /** PlayerState */
        PlayerState: {
            /** Display Name */
            display_name: string;
            /** Location Id */
            location_id: string;
            /** Traits */
            traits?: string[];
        };
        /** PromiseState */
        PromiseState: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Promisee Id */
            promisee_id: string;
            /** Content */
            content: string;
            /** Deadline Day */
            deadline_day: number;
            /**
             * Deadline Phase
             * @enum {string}
             */
            deadline_phase: "morning" | "afternoon" | "evening" | "night";
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "kept" | "broken";
        };
        /** RunSnapshot */
        RunSnapshot: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Seed */
            seed: number;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "completed";
            /**
             * Day
             * @default 1
             */
            day: number;
            /**
             * Phase
             * @default morning
             * @enum {string}
             */
            phase: "morning" | "afternoon" | "evening" | "night";
            /**
             * Action Count
             * @default 0
             */
            action_count: number;
            /**
             * World Tick
             * @default 0
             */
            world_tick: number;
            /**
             * Weather
             * @default clear
             * @enum {string}
             */
            weather: "clear" | "rain";
            player: components["schemas"]["PlayerState"];
            /** Locations */
            locations: components["schemas"]["LocationState"][];
            /** Npcs */
            npcs: components["schemas"]["NpcState"][];
            /** Promises */
            promises?: components["schemas"]["PromiseState"][];
            dialogue?: components["schemas"]["DialogueState"] | null;
            /** Recent Events */
            recent_events?: components["schemas"]["WorldEvent"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorldEvent */
        WorldEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /**
             * Visible
             * @default true
             */
            visible: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_v1_runs__run_id__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_action_v1_runs__run_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
